env:
  global:
    - CC_TEST_REPORTER_ID=5bf1273a9f1adfb6a71d01e7b38897f4f6c8a082e2128b8d4381253d375f58fc
language: ruby
rvm:
 - 2.2.2
services:
 - postgresql
 - redis-server
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
scripts:
  - bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT